export const types = {
  FETCHING_DATA_IN_PROGRESS: 'FETCHING_DATA_IN_PROGRESS',
  FETCHING_DATA_COMPLETED: 'FETCHING_DATA_COMPLETED',
  RESET: 'RESET',
  RESPONSE_DATA_SUCCESSFULLY_RECEIVED: 'RESPONSE_DATA_SUCCESSFULLY_RECEIVED',
  API_ERROR_RECEIVED: 'API_ERROR_RECEIVED',
  RESET_RESPONSE_DATA: 'RESET_RESPONSE_DATA',
  PATHLAYER_DATA_SET: 'PATHLAYER_DATA_SET',
  ICONLAYER_DATA_SET: 'ICONLAYER_DATA_SET',
  TEXTLAYER_DATA_SET: 'TEXTLAYER_DATA_SET',
  VIEWSTATE_DATA_SET: 'VIEWSTATE_DATA_SET'
};
